### Carga de Librerías

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)

Matplotlib is building the font cache; this may take a moment.

## Carga de datos

#### Exploración inicial para conocer su dimensión y estructura. En esta fase analizaremos el número de filas, columnas y variables, así como el tipo de información que contiene el dataset.

In [2]:
df = pd.read_csv("../data/raw/resortworldwide.csv")
df.head()

,URL,Rate,NameResort,Stars,Km Freeride,Continent,Country,State/Province,Altitude,Easy,Intermediate,Difficult,Adult,Currency,Ski resort size,"Slope offering, variety of runs",Lifts and cable cars,Snow reliability,"Access, on-site parking","Orientation (trail map, information boards, sign-postings)",Cleanliness and hygiene,Environmentally friendly ski operation,"Mountain restaurants, ski huts, gastronomy",Après-ski,Accommodation offering directly at the slopes and lifts,Families and children,Beginners,Snow parks,Cross-country skiing and trails,country,latitude,longitude,Total Kms
0,http://www.skiresort.info/ski-resort/kitzski-k...,4.9,KitzSki – Kitzbühel/Kirchberg,5.0,45.0,Europe,Austria,Tyrol (Tirol),2000.0,101.0,61.0,17.0,55,European Euro,"5,0",5.0,"5,0",5.0,"4,0","5,0","5,0","4,0","5,0","4,0","5,0","5,0","5,0","5,0","5,0",AT,47.516231,14.550072,179
1,http://www.skiresort.info/ski-resort/ischglsam...,4.8,Ischgl/Samnaun – Silvretta Arena,5.0,15.0,Europe,Austria,Tyrol (Tirol),2872.0,47.0,142.0,49.0,53,European Euro,"5,0",5.0,"5,0",5.0,"4,0","5,0","5,0","4,0","5,0","5,0","5,0","4,0","4,0","5,0","4,0",AT,47.516231,14.550072,238
2,http://www.skiresort.info/ski-resort/skiwelt-w...,4.8,SkiWelt Wilder Kaiser-Brixental,5.0,26.0,Europe,Austria,Tyrol (Tirol),1957.0,122.0,129.0,33.0,49,European Euro,"5,0",5.0,"5,0",4.0,"5,0","4,0","5,0","5,0","5,0","4,0","4,0","5,0","5,0","5,0","5,0",AT,47.516231,14.550072,284
3,http://www.skiresort.info/ski-resort/st-antons...,4.8,Ski Arlberg,5.0,200.0,Europe,Austria,Tyrol (Tirol),2811.0,132.0,123.0,50.0,53,European Euro,"5,0",5.0,"5,0",5.0,"4,0","4,0","4,0","4,0","5,0","5,0","5,0","5,0","5,0","4,0","4,0",AT,47.516231,14.550072,305
4,http://www.skiresort.info/ski-resort/serfaus-f...,4.8,Serfaus-Fiss-Ladis,5.0,28.0,Europe,Austria,Tyrol (Tirol),2820.0,47.0,123.0,28.0,51,European Euro,"5,0",5.0,"5,0",5.0,"4,0","5,0","4,0","4,0","5,0","4,0","4,0","5,0","4,0","5,0","4,0",AT,47.516231,14.550072,198

In [3]:
df.shape

(5478, 33)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5478 entries, 0 to 5477
Data columns (total 33 columns):
 #   Column                                                       Non-Null Count  Dtype
---  ------                                                       --------------  -----
 0   URL                                                          5478 non-null   str
 1   Rate                                                         3471 non-null   float64
 2   NameResort                                                   5478 non-null   str
 3   Stars                                                        413 non-null    float64
 4   Km Freeride                                                  480 non-null    float64
 5   Continent                                                    5469 non-null   str
 6   Country                                                      5469 non-null   str
 7   State/Province                                               5469 non-null   str
 8   Altitude                                                     5469 non-null   float64
 9   Easy                                                         5478 non-null   float64
 10  Intermediate                                                 5478 non-null   float64
 11  Difficult                                                    5478 non-null   float64
 12  Adult                                                        5469 non-null   str
 13  Currency                                                     5469 non-null   str
 14  Ski resort size                                              3452 non-null   str
 15  Slope offering, variety of runs                              3452 non-null   float64
 16  Lifts and cable cars                                         3452 non-null   str
 17  Snow reliability                                             429 non-null    float64
 18  Access, on-site parking                                      429 non-null    str
 19  Orientation (trail map, information boards, sign-postings)   429 non-null    str
 20  Cleanliness and hygiene                                      429 non-null    str
 21  Environmentally friendly ski operation                       429 non-null    str
 22  Mountain restaurants, ski huts, gastronomy                   429 non-null    str
 23  Après-ski                                                    429 non-null    str
 24  Accommodation offering directly at the slopes and lifts      429 non-null    str
 25  Families and children                                        429 non-null    str
 26  Beginners                                                    429 non-null    str
 27  Snow parks                                                   429 non-null    str
 28  Cross-country skiing and trails                              429 non-null    str
 29  country                                                      4879 non-null   str
 30  latitude                                                     4880 non-null   float64
 31  longitude                                                    4880 non-null   float64
 32  Total Kms                                                    5478 non-null   int64
dtypes: float64(11), int64(1), str(21)
memory usage: 1.4 MB

In [5]:
df.describe()

,Rate,Stars,Km Freeride,Altitude,Easy,Intermediate,Difficult,"Slope offering, variety of runs",Snow reliability,latitude,longitude,Total Kms
count,3471.000000,413.000000,480.000000,5469.000000,5478.000000,5478.000000,5478.000000,3452.000000,429.000000,4880.000000,4880.000000,5478.000000
mean,1.905733,2.970944,2.448958,1017.293107,4.016119,4.548266,2.026908,1.954287,3.850816,45.651246,27.153449,10.390471
std,0.940525,1.356082,10.217407,822.678565,11.666099,13.266404,6.697797,1.054178,1.113272,13.995871,57.856092,28.819054
min,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,-40.900557,-106.346771,0.000000
25%,1.200000,2.000000,0.000000,410.000000,0.300000,0.000000,0.000000,1.000000,3.000000,41.871940,10.451526,0.000000
50%,1.500000,3.000000,0.000000,843.000000,1.000000,0.500000,0.000000,1.600000,4.000000,47.516231,14.550072,1.000000
75%,2.500000,4.000000,3.000000,1500.000000,3.000000,3.400000,1.000000,2.600000,5.000000,51.165691,24.966760,9.000000
max,5.000000,5.000000,200.000000,5000.000000,312.000000,239.000000,126.000000,5.000000,5.000000,71.706936,174.885971,600.000000

## Valores Nulos

In [6]:
df.isnull().sum()

URL                                                               0
Rate                                                           2007
NameResort                                                        0
Stars                                                          5065
Km Freeride                                                    4998
Continent                                                         9
Country                                                           9
State/Province                                                    9
Altitude                                                          9
Easy                                                              0
Intermediate                                                      0
Difficult                                                         0
Adult                                                             9
Currency                                                          9
Ski resort size                                                2026
Slope offering, variety of runs                                2026
Lifts and cable cars                                           2026
Snow reliability                                               5049
Access, on-site parking                                        5049
Orientation (trail map, information boards, sign-postings)     5049
Cleanliness and hygiene                                        5049
Environmentally friendly ski operation                         5049
Mountain restaurants, ski huts, gastronomy                     5049
Après-ski                                                      5049
Accommodation offering directly at the slopes and lifts        5049
Families and children                                          5049
Beginners                                                      5049
Snow parks                                                     5049
Cross-country skiing and trails                                5049
country                                                         599
latitude                                                        598
longitude                                                       598
Total Kms                                                         0
dtype: int64

In [7]:
(df.isnull().sum() / len(df) * 100).sort_values(ascending=False)

Stars                                                          92.460752
Accommodation offering directly at the slopes and lifts        92.168675
Après-ski                                                      92.168675
Mountain restaurants, ski huts, gastronomy                     92.168675
Environmentally friendly ski operation                         92.168675
Cross-country skiing and trails                                92.168675
Snow parks                                                     92.168675
Beginners                                                      92.168675
Families and children                                          92.168675
Cleanliness and hygiene                                        92.168675
Orientation (trail map, information boards, sign-postings)     92.168675
Access, on-site parking                                        92.168675
Snow reliability                                               92.168675
Km Freeride                                                    91.237678
Ski resort size                                                36.984301
Lifts and cable cars                                           36.984301
Slope offering, variety of runs                                36.984301
Rate                                                           36.637459
country                                                        10.934648
longitude                                                      10.916393
latitude                                                       10.916393
Adult                                                           0.164294
State/Province                                                  0.164294
Continent                                                       0.164294
Currency                                                        0.164294
Altitude                                                        0.164294
Country                                                         0.164294
URL                                                             0.000000
NameResort                                                      0.000000
Intermediate                                                    0.000000
Easy                                                            0.000000
Difficult                                                       0.000000
Total Kms                                                       0.000000
dtype: float64

In [8]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Rate,3471.0,1.905733,0.940525,0.000000,1.200000,1.500000,2.500000,5.000000
Stars,413.0,2.970944,1.356082,1.000000,2.000000,3.000000,4.000000,5.000000
Km Freeride,480.0,2.448958,10.217407,0.000000,0.000000,0.000000,3.000000,200.000000
Altitude,5469.0,1017.293107,822.678565,0.000000,410.000000,843.000000,1500.000000,5000.000000
Easy,5478.0,4.016119,11.666099,0.000000,0.300000,1.000000,3.000000,312.000000
Intermediate,5478.0,4.548266,13.266404,0.000000,0.000000,0.500000,3.400000,239.000000
Difficult,5478.0,2.026908,6.697797,0.000000,0.000000,0.000000,1.000000,126.000000
"Slope offering, variety of runs",3452.0,1.954287,1.054178,0.000000,1.000000,1.600000,2.600000,5.000000
Snow reliability,429.0,3.850816,1.113272,1.000000,3.000000,4.000000,5.000000,5.000000
latitude,4880.0,45.651246,13.995871,-40.900557,41.871940,47.516231,51.165691,71.706936
longitude,4880.0,27.153449,57.856092,-106.346771,10.451526,14.550072,24.966760,174.885971
Total Kms,5478.0,10.390471,28.819054,0.000000,0.000000,1.000000,9.000000,600.000000

In [9]:
df.describe(include="object").T

C:\Users\dieve\AppData\Local\Temp\ipykernel_3920\1274302342.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object").T

,count,unique,top,freq
URL,5478,5478,http://www.skiresort.info/ski-resort/kitzski-k...,1
NameResort,5478,5478,KitzSki – Kitzbühel/Kirchberg,1
Continent,5469,6,Europe,3571
Country,5469,90,Germany,715
State/Province,5469,418,Honshu,464
Adult,5469,424,0,1952
Currency,5469,42,-,1952
Ski resort size,3452,42,"1,3",626
Lifts and cable cars,3452,41,"1,5",1029
"Access, on-site parking",429,5,"3,0",171
"Orientation (trail map, information boards, sign-postings)",429,5,"4,0",210
Cleanliness and hygiene,429,4,"4,0",316
Environmentally friendly ski operation,429,5,"4,0",240
"Mountain restaurants, ski huts, gastronomy",429,5,"4,0",171
Après-ski,429,5,"3,0",174
Accommodation offering directly at the slopes and lifts,429,5,"3,0",110
Families and children,429,5,"4,0",179
Beginners,429,5,"4,0",166
Snow parks,429,5,"1,0",107
Cross-country skiing and trails,429,5,"3,0",139
country,4879,78,DE,715

#### Tras la exploración inicial se observa que el dataset cuenta con un volumen de datos suficiente para realizar el análisis. No existen registros duplicados, aunque varias variables presentan un porcentaje elevado de valores nulos que deberán estudiarse durante el preprocesamiento para decidir si conviene eliminarlas o arreglarlas.